Week4
hepnerthomas/metana-bootcamp pull request #5
Opened 2023-04-14 03:48 UTC by hepnerthomas

2023-04-15 18:54 UTC, dhruvinparikh requested changes

2023-04-15 18:54 UTC, dhruvinparikh commented on week1/test/Token.js
> +        expect(await await ethers.provider.getBalance(hardhatToken.address)).to.equal(parseEther("1.0"));
- [ ] assert expected  eth balance for `addr`

2023-04-15 18:54 UTC, dhruvinparikh commented on week1/test/Token.js
> +        await expect(hardhatToken.connect(addr1).sellBack(tokensToRefundFormatted)).to.be.revertedWith("Not enough tokens");
- [ ] assert the eth balance of seller
- [ ] assert token balance of seller
- [ ] assert eth balance of token sale contract

2023-04-15 18:54 UTC, dhruvinparikh commented on week1/test/Token.js
> +
- [ ] Also assert ETH balance in "Withdraw ETH" case.

2023-04-15 18:54 UTC, dhruvinparikh commented on week3/test/ForgeMetals.js
> +      await expect(balanceMetalId2).to.equal(0);
```suggestion
      await expect(balanceMetalId1).to.equal(oldBalanceMetalId1 - 1);
      await expect(balanceMetalId2).to.equal(oldBalanceMetalId2 - 1);
```

2023-04-15 18:54 UTC, dhruvinparikh commented on week3/test/ForgeMetals.js
> +
you can load fixture in `beforeEach` hook

2023-04-16 17:46 UTC, hepnerthomas commented on week1/test/Token.js
> +        expect(await await ethers.provider.getBalance(hardhatToken.address)).to.equal(parseEther("1.0"));
done

2023-04-16 18:22 UTC, hepnerthomas commented on week1/test/Token.js
> +        await expect(hardhatToken.connect(addr1).sellBack(tokensToRefundFormatted)).to.be.revertedWith("Not enough tokens");
done

2023-04-16 18:53 UTC, hepnerthomas commented on week1/test/Token.js
> +
done

2023-04-16 19:14 UTC, hepnerthomas commented on week3/test/ForgeMetals.js
> +      await expect(balanceMetalId2).to.equal(0);
done

2023-04-16 19:19 UTC, hepnerthomas commented on week3/test/ForgeMetals.js
> +
done

2023-04-16 19:20 UTC, merged